openapi: 3.0.0
info:
  title: Tes Masif
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
    description: DEVELOPMENT
  - url: 'https://api.rapidtest.digitalservice.id'
    description: STAGING
paths:
  /api/login:
    post:
      summary: ''
      operationId: post-api-login
      responses:
        '200':
          description: OK
components:
  schemas: {}
